spring.application.name=steam-stats-backend
spring.threads.virtual.enabled=true
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true

# Config hibernate show sql for debugging purposes
#spring.jpa.properties.hibernate.format_sql=true

#Config postgres database connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

#Config hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Config steam api key
steam.api.key=${STEAM_API_KEY:your_steam_api_key_here}

#Config swagger
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}

#Rate limiting configuration
server.forward-headers-strategy=framework
resilience4j.ratelimiter.configs.default.limit-for-period=50
resilience4j.ratelimiter.configs.default.limit-refresh-period=30s
resilience4j.ratelimiter.configs.default.timeout-duration=0s